/**
 * FRONTIER FILL - register the August 2026 frontier arms and generate their
 * frozen-benchmark outputs. Generic on purpose: the generate step takes ANY
 * candidate slug list and reproduces, per candidate, the exact serving path
 * the arena would use for it, so future arms need registration only.
 *
 * THREE SERVING PATHS, EACH MIRRORED FROM ITS SOURCE OF TRUTH
 * -----------------------------------------------------------
 *   baseline  generateForCandidate(candidate, { userMessage }) - nothing else.
 *   rag-v1    the chat route's assembly (src/app/api/arena/chat/route.ts):
 *             searchRag(prompt, 'igala', 4) chunks + retrieveGoldExamples(k=8)
 *             over the route's own gold pool query, with the REAL prompt
 *             identity so the contamination guard sees the true cuid.
 *   rag-v2    scripts/sniff-test-v2.ts's generation leg: buildRetrievalV2 on
 *             the prompt's human slug, buildUserTurnV2, IGALA_SYSTEM_V2, gold
 *             exemplars as prior turns.
 *
 * An output generated here must be indistinguishable from one generated by
 * the routes - otherwise the frozen-bank numbers describe a system nobody can
 * chat with, which is the exact failure the chat route's comments warn about.
 *
 * IDEMPOTENT AND RESUMABLE: existing outputs are skipped, so a crashed or
 * key-starved run resumes rather than double-pays. Per-candidate isolation:
 * one dead provider (the Anthropic key today) must not stop the other arms -
 * each candidate is probed with a 1-token call first and skipped with the
 * exact provider error in the final report.
 *
 * Usage (from web/):
 *   npx tsx --env-file=.env.local scripts/frontier-fill.ts register
 *   npx tsx --env-file=.env.local scripts/frontier-fill.ts generate [slug ...]
 *   npx tsx --env-file=.env.local scripts/frontier-fill.ts all [slug ...]
 * generate/all default to the six frontier slugs when no slugs are given.
 */

import type { EvalBucket } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import {
  generateForCandidate,
  type CandidateLike,
  type GoldExample,
  type RagChunk,
} from "@/lib/arena/providers";
import {
  retrieveGoldExamples,
  type GoldPoolEntry,
} from "@/lib/arena/gold-retrieval";
import { searchRag } from "@/lib/rag";
import {
  buildRetrievalV2,
  type RetrievalV2Result,
} from "@/lib/arena/retrieval-v2";
import { IGALA_SYSTEM_V2, buildUserTurnV2 } from "@/lib/generation-prompt-v2";
import { estimateGenerationCostUsd, roundUsd } from "@/lib/arena/pricing";
import {
  FRONTIER_SLUGS,
  FRONTIER_TARGETS,
  servingModeFor,
} from "@/lib/arena/frontier-targets";

/** Same K values as the chat route - the composition being reproduced. */
const GOLD_K = 8;
const RAG_K = 4;

function log(...args: unknown[]) {
  console.log(...args);
}

function keyForProvider(provider: string): string | undefined {
  switch (provider) {
    case "anthropic":
      return process.env.ANTHROPIC_API_KEY;
    case "openai":
      return process.env.OPENAI_API_KEY;
    case "google":
      return process.env.GOOGLE_GENERATIVE_AI_API_KEY;
    case "openai-compatible":
      return (
        process.env.OPENAI_COMPATIBLE_API_KEY ?? process.env.TOGETHER_API_KEY
      );
    default:
      return undefined;
  }
}

// ─── REGISTER ───────────────────────────────────────────────────────────────

async function register() {
  // Upsert in list order: rag-v2 rows resolve parentCandidateId from the v1
  // sibling upserted just before them (order guaranteed by the unit tests).
  const idBySlug = new Map<string, string>();
  for (const t of FRONTIER_TARGETS) {
    const parentCandidateId = t.parentSlug
      ? (idBySlug.get(t.parentSlug) ?? null)
      : null;
    const data = {
      name: t.name,
      family: t.family,
      provider: t.provider,
      baseModelId: t.baseModelId,
      kind: t.kind,
      ragEnabled: t.ragEnabled,
      versionLabel: t.versionLabel,
      decodingParams: t.decodingParams,
      color: t.color,
      apiEndpoint: null,
      parentCandidateId,
      language: "igala",
      // Every arm in the comparison must be servable by the arena.
      archived: false,
    };
    const existing = await prisma.candidateModel.findUnique({
      where: { slug: t.slug },
      select: { id: true },
    });
    const row = await prisma.candidateModel.upsert({
      where: { slug: t.slug },
      update: data,
      create: { ...data, slug: t.slug, isPublic: true },
      select: { id: true },
    });
    idBySlug.set(t.slug, row.id);
    log(
      `  ${existing ? "updated" : "CREATED"}  ${t.slug.padEnd(26)} ${t.name}`,
    );
  }

  // Gemini 2.5 Pro is closed to new projects: its candidates can no longer be
  // served, and a selectable dead row in chat has burned reviewers before.
  // Archive by baseModelId so any 2.5-Pro row is caught; the 2.5 Flash rows
  // hold real n=22 data and are deliberately untouched.
  const archived = await prisma.candidateModel.updateMany({
    where: { baseModelId: "gemini-2.5-pro", archived: false },
    data: { archived: true },
  });
  log(`\n  archived ${archived.count} gemini-2.5-pro candidate(s)`);
}

// ─── RETRIEVAL (shared per prompt, cached across candidates) ────────────────

interface FrozenPrompt {
  id: string;
  promptId: string;
  text: string;
  bucket: EvalBucket | null;
}

async function frozenPrompts(): Promise<FrozenPrompt[]> {
  return prisma.prompt.findMany({
    where: { isHoldout: true, language: "igala" },
    select: { id: true, promptId: true, text: true, bucket: true },
    orderBy: { promptId: "asc" },
  });
}

/**
 * Mirror of the chat route's loadGoldPool() (src/app/api/arena/chat/route.ts):
 * demo rows out, consentTraining honoured IN THE QUERY, isHoldout taken from
 * the prompt. Duplicated here rather than imported because the route does not
 * export it; if the route's query changes, this must change with it.
 */
async function loadGoldPool(): Promise<GoldPoolEntry[]> {
  const rows = await prisma.coldAuthorAnswer.findMany({
    where: { isDemo: false, consentTraining: true },
    select: {
      id: true,
      promptId: true,
      answerText: true,
      bucket: true,
      consentTraining: true,
      isDemo: true,
      verificationStatus: true,
      prompt: {
        select: { promptId: true, text: true, isHoldout: true, bucket: true },
      },
    },
  });
  return rows.map((r) => ({
    id: r.id,
    promptId: r.promptId,
    promptRef: r.prompt.promptId,
    promptText: r.prompt.text,
    answerText: r.answerText,
    bucket: r.bucket ?? r.prompt.bucket,
    isHoldout: r.prompt.isHoldout,
    isDemo: r.isDemo,
    consentTraining: r.consentTraining,
    verificationStatus: r.verificationStatus,
  }));
}

interface V1Retrieval {
  ragContext: RagChunk[];
  goldExamples: GoldExample[];
}

/** v1 assembly for one frozen prompt, exactly as the chat route builds it. */
async function v1RetrievalFor(
  prompt: FrozenPrompt,
  pool: GoldPoolEntry[],
): Promise<V1Retrieval> {
  let ragContext: RagChunk[] = [];
  try {
    const entries = await searchRag(prompt.text, "igala", RAG_K);
    ragContext = entries.map((e) => ({
      id: e.id,
      content: e.content,
      topic: e.topic,
      chunkType: e.chunkType,
    }));
  } catch (e) {
    // The route degrades to no chunks; a benchmark run should not do so
    // silently, so the degradation is loud even though the behaviour matches.
    log(
      `  !! searchRag unavailable for ${prompt.promptId}: ${(e as Error).message}`,
    );
  }

  const retrieved = retrieveGoldExamples(
    // The REAL prompt identity - cuid, text, bucket - with isHoldout true, so
    // both contamination rules fire exactly as they do when the route serves
    // this prompt.
    {
      promptId: prompt.id,
      text: prompt.text,
      bucket: prompt.bucket,
      isHoldout: true,
    },
    pool,
    { k: GOLD_K },
  );
  // Hard assertion, same policy as igala-rag-run.ts: refuse to spend a cent
  // on a contaminated prompt rather than storing an output that would poison
  // the benchmark.
  for (const ex of retrieved.examples) {
    if (ex.promptId === prompt.id) {
      throw new Error(
        `CONTAMINATION: retrieval returned the prompt's own gold (${ex.id})`,
      );
    }
  }

  return {
    ragContext,
    goldExamples: retrieved.examples.map((e) => ({
      id: e.id,
      question: e.question,
      answer: e.answer,
    })),
  };
}

// ─── GENERATE ───────────────────────────────────────────────────────────────

interface CandidateReport {
  slug: string;
  mode: string;
  created: number;
  existing: number;
  failed: number;
  costUsd: number;
  tokensIn: number;
  tokensOut: number;
  skipped: string | null;
}

async function generate(slugs: string[]) {
  const prompts = await frozenPrompts();
  log(`frozen prompts: ${prompts.length}\n`);

  const candidates = await prisma.candidateModel.findMany({
    where: { slug: { in: slugs } },
  });
  const bySlug = new Map(candidates.map((c) => [c.slug, c]));

  // Retrieval is deterministic per prompt, so one build serves every
  // candidate on the same serving path (searchRag costs an embedding call and
  // buildRetrievalV2 several queries - do each once, not once per arm).
  let goldPool: GoldPoolEntry[] | null = null;
  const v1Cache = new Map<string, V1Retrieval>();
  const v2Cache = new Map<string, RetrievalV2Result>();

  const reports: CandidateReport[] = [];

  for (const slug of slugs) {
    const candidate = bySlug.get(slug);
    const report: CandidateReport = {
      slug,
      mode: candidate ? servingModeFor(candidate) : "?",
      created: 0,
      existing: 0,
      failed: 0,
      costUsd: 0,
      tokensIn: 0,
      tokensOut: 0,
      skipped: null,
    };
    reports.push(report);

    if (!candidate) {
      report.skipped = "not registered - run the register step first";
      log(`\n== ${slug}: SKIPPED (${report.skipped})`);
      continue;
    }
    if (candidate.archived) {
      // Never spend on a row the arena will not serve.
      report.skipped = "archived candidate";
      log(`\n== ${slug}: SKIPPED (archived)`);
      continue;
    }
    const decoding = (candidate.decodingParams ?? {}) as Record<
      string,
      unknown
    >;
    if (decoding.temperature !== 0 && decoding.temperature !== null) {
      // Same trust-but-verify as sniff-test-v2: a silently non-zero
      // temperature would make every cross-arm comparison partly a decoding
      // comparison. Skip this arm rather than abort the run. null is the one
      // sanctioned exception: Claude Opus 5 REJECTS the temperature parameter
      // ("`temperature` is deprecated for this model"), so its rows opt out
      // explicitly and providers.ts omits the field. Greedy-equivalent
      // decoding is the provider default there, which is as close to 0 as
      // that API allows.
      report.skipped = `temperature is ${String(decoding.temperature)}, expected 0 (or null for models that reject the parameter) - re-run the register step`;
      log(`\n== ${slug}: SKIPPED (${report.skipped})`);
      continue;
    }
    if (!keyForProvider(candidate.provider)) {
      report.skipped = `no API key for provider "${candidate.provider}"`;
      log(`\n== ${slug}: SKIPPED (${report.skipped})`);
      continue;
    }

    const mode = servingModeFor(candidate);
    log(`\n== ${candidate.name} (${candidate.baseModelId})  [${mode}]`);

    // One cheap probe before committing to 43 calls: a dead key or an
    // unserved model id should cost one failed request and one clear line,
    // not 43 identical errors. The probe error is reported verbatim because
    // "which exact error did Anthropic return" is part of the deliverable.
    try {
      await generateForCandidate(
        {
          provider: candidate.provider,
          baseModelId: candidate.baseModelId,
          apiEndpoint: candidate.apiEndpoint,
          // The probe reuses the CANDIDATE's decoding rather than pinning its
          // own: hardcoding temperature 0 here made the probe reject Claude
          // Opus 5 (which refuses the parameter) even after the candidate row
          // had correctly opted out with temperature null.
          decodingParams: { ...decoding, maxTokens: 32 },
        },
        { userMessage: "hi" },
      );
    } catch (e) {
      report.skipped = `provider probe failed: ${(e as Error).message.slice(0, 300)}`;
      log(`  SKIPPED - ${report.skipped}`);
      continue;
    }

    const existing = await prisma.modelOutput.findMany({
      where: { candidateModelId: candidate.id, isDemo: false },
      select: { promptId: true },
    });
    const done = new Set(existing.map((e) => e.promptId));

    let consecutiveFailures = 0;
    for (const prompt of prompts) {
      if (done.has(prompt.id)) {
        report.existing++;
        continue;
      }
      try {
        let gen;
        let ragContextIds: string[];

        if (mode === "rag-v2") {
          if (!v2Cache.has(prompt.promptId)) {
            v2Cache.set(
              prompt.promptId,
              // The human slug, not the cuid - buildRetrievalV2's leak guard
              // keys its protected set on prompt slugs (see retrieval-v2.ts
              // and sniff-test-v2.ts, which this leg mirrors).
              await buildRetrievalV2(prisma, {
                promptId: prompt.promptId,
                text: prompt.text,
                bucket: prompt.bucket,
                isHoldout: true,
              }),
            );
          }
          const v2 = v2Cache.get(prompt.promptId)!;
          gen = await generateForCandidate(candidate as CandidateLike, {
            userMessage: buildUserTurnV2(prompt.text, v2, prompt.bucket),
            goldExamples: v2.exampleTurns,
            systemPromptOverride: IGALA_SYSTEM_V2,
          });
          // v2's audit trail is the full lex:/pp:/gold: id list from the
          // assembly, not the (id-less) exampleTurns the provider saw.
          ragContextIds = v2.contextIds;
        } else if (mode === "rag-v1") {
          goldPool ??= await loadGoldPool();
          if (!v1Cache.has(prompt.id)) {
            v1Cache.set(prompt.id, await v1RetrievalFor(prompt, goldPool));
          }
          const v1 = v1Cache.get(prompt.id)!;
          gen = await generateForCandidate(candidate as CandidateLike, {
            userMessage: prompt.text,
            ragContext: v1.ragContext,
            goldExamples: v1.goldExamples,
          });
          ragContextIds = gen.ragContextIds;
        } else {
          gen = await generateForCandidate(candidate as CandidateLike, {
            userMessage: prompt.text,
          });
          ragContextIds = gen.ragContextIds;
        }

        await prisma.modelOutput.create({
          data: {
            promptId: prompt.id,
            model: candidate.family,
            modelId: gen.modelId,
            candidateModelId: candidate.id,
            bucket: prompt.bucket,
            outputText: gen.text,
            ragContextIds,
            tokenCountIn: gen.tokensIn ?? null,
            tokenCountOut: gen.tokensOut ?? null,
            latencyMs: gen.latencyMs,
            isDemo: false,
          },
        });
        report.costUsd += estimateGenerationCostUsd({
          modelId: gen.modelId,
          tokensIn: gen.tokensIn,
          tokensOut: gen.tokensOut,
        });
        report.tokensIn += gen.tokensIn ?? 0;
        report.tokensOut += gen.tokensOut ?? 0;
        report.created++;
        consecutiveFailures = 0;
        log(
          `  ok  ${prompt.promptId.padEnd(22)} ${gen.text.replace(/\s+/g, " ").slice(0, 60)}`,
        );
      } catch (e) {
        report.failed++;
        consecutiveFailures++;
        log(`  ERR ${prompt.promptId}: ${(e as Error).message.slice(0, 160)}`);
        // A dead key or wrong model id fails on every prompt; bail rather
        // than burning 43 identical errors (same policy as igala-rag-run.ts).
        if (consecutiveFailures >= 3 && report.created === 0) {
          report.skipped = `abandoned after 3 consecutive failures: ${(e as Error).message.slice(0, 200)}`;
          log(`  -> abandoning ${slug} after 3 consecutive failures`);
          break;
        }
      }
    }
  }

  // ─── report ──────────────────────────────────────────────────────────────
  log("\n\nFRONTIER FILL SUMMARY");
  let totalCost = 0;
  let totalIn = 0;
  let totalOut = 0;
  for (const r of reports) {
    totalCost += r.costUsd;
    totalIn += r.tokensIn;
    totalOut += r.tokensOut;
    const counts = `created=${String(r.created).padStart(2)} existing=${String(r.existing).padStart(2)} failed=${String(r.failed).padStart(2)}`;
    const tail = r.skipped
      ? `SKIPPED: ${r.skipped}`
      : `~$${roundUsd(r.costUsd).toFixed(2)}  (${r.tokensIn} in / ${r.tokensOut} out)`;
    log(`  ${r.slug.padEnd(26)} [${r.mode.padEnd(8)}] ${counts}  ${tail}`);
  }
  log(
    `\nTokens this run: ${totalIn} in, ${totalOut} out. Estimated spend ~$${roundUsd(totalCost).toFixed(2)} ` +
      `(rates from src/lib/arena/pricing.ts; model ids missing from its table fall back to the $1/$3 default, so treat this as rough).`,
  );
}

// ─── entrypoint ─────────────────────────────────────────────────────────────

async function main() {
  const [step, ...rest] = process.argv.slice(2);
  const slugs = rest.length > 0 ? rest : FRONTIER_SLUGS;
  switch (step) {
    case "register":
      await register();
      break;
    case "generate":
      await generate(slugs);
      break;
    case "all":
      await register();
      await generate(slugs);
      break;
    default:
      log("Usage: frontier-fill.ts <register|generate|all> [slug ...]");
      process.exitCode = 1;
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
