/**
 * TRAIN QUEUE FILL - the 2026-08-20 annotation pivot's generation step
 * (tasks/annotation-pivot-decision.md). Two jobs:
 *
 *   pool      Flag the decided pairing-pool arms on CandidateModel
 *             (inPairingPool = true; everything else false). The queue routes
 *             read the FLAG per request, never a slug list - this script is
 *             the one place the decision's arm names appear.
 *   generate  Produce the pool arms' outputs on the TRAIN prompts (the
 *             opposite target of scripts/frontier-fill.ts, which fills the
 *             frozen holdout bank). Zero-gold prompts first (tranche 1):
 *             every episode there mints first gold AND a strong-pair
 *             preference AND a correction - the maximum-yield episode.
 *
 * SERVING PATHS are mirrored from frontier-fill.ts, which mirrors them from
 * the routes: baseline / rag-v1 (chat-route assembly) / rag-v2 / rag-v3.
 * An output generated here must be indistinguishable from one generated by
 * the arena for the same candidate.
 *
 * CONTAMINATION POLICY ON TRAIN PROMPTS: the frozen-bank leak guard is not
 * needed here (nothing scored against these prompts), but two refusals stay:
 *   - own-gold exclusion: retrieval never returns the prompt's own gold, so
 *     no model parrots a speaker's answer back at its author (rule 1 in
 *     gold-retrieval.ts is unconditional; the hard assertion below proves it
 *     fired);
 *   - holdout gold stays excluded from exemplars (allowHoldoutSources is
 *     never passed), so the benchmark is not used to build the system under
 *     test.
 *
 * THE $15 HARD CAP is enforced by RULE, not estimate (pricing.ts now carries
 * gemini-3.1-pro's real $2/$12 rate, so the worst case priced below is the
 * real one, not the old $1/$3 default floor):
 *   - maxTokens per provider - 1024 for Claude (bounds its worst case),
 *     4096 for Gemini (whose reasoning trace bills against the completion
 *     budget; see trainMaxTokensFor) - and the worst-case pricing below uses
 *     the same numbers;
 *   - generation runs in slices of ~60 prompts;
 *   - after each slice, MEASURED spend is recomputed from the stored
 *     tokenCountIn/Out of every pool-arm output on train prompts (so re-runs
 *     never reset the budget) and logged to CostEntry;
 *   - the next slice starts only while
 *       measured-so-far + worst-case(next slice) <= $15,
 *     where worst-case assumes every remaining call bills WORST_CASE_IN
 *     input tokens and the full maxTokens output at pricing.ts rates.
 * Worst case the run halts partway through the bank; it can never cross $15.
 *
 * IDEMPOTENT AND RESUMABLE: existing outputs are skipped; a crashed or
 * key-starved run resumes rather than double-pays. Per-candidate isolation:
 * each candidate is probed with a 1-token call first and skipped with the
 * exact provider error in the final report (a dead Anthropic key must not
 * stop the Gemini arms).
 *
 * Usage (from web/):
 *   npx tsx --env-file=.env.local scripts/train-queue-fill.ts pool
 *   npx tsx --env-file=.env.local scripts/train-queue-fill.ts generate [slug ...]
 *   npx tsx --env-file=.env.local scripts/train-queue-fill.ts all [slug ...]
 * generate/all default to the arms flagged inPairingPool in the DB.
 */

import type { EvalBucket } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import {
  generateForCandidate,
  type CandidateLike,
  type GoldExample,
  type RagChunk,
} from "@/lib/arena/providers";
import {
  retrieveGoldExamples,
  type GoldPoolEntry,
} from "@/lib/arena/gold-retrieval";
import { searchRag } from "@/lib/rag";
import {
  buildRetrievalV2,
  type RetrievalV2Result,
} from "@/lib/arena/retrieval-v2";
import { IGALA_SYSTEM_V2, buildUserTurnV2 } from "@/lib/generation-prompt-v2";
import { IGALA_SYSTEM_V3 } from "@/lib/generation-prompt-v3";
import {
  estimateGenerationCostUsd,
  priceForModel,
  roundUsd,
} from "@/lib/arena/pricing";
import { servingModeFor } from "@/lib/arena/frontier-targets";

/**
 * The decided pairing pool (decision doc, "Arms that feed the pairwise
 * queue"): each family's best arm from the 2026-08-20 leak audit, plus the
 * bare Gemini as the direct human test of the METHOD v3 prompt. This list
 * exists ONLY to set the DB flag; every runtime consumer reads the flag.
 */
const DECIDED_POOL_SLUGS = [
  "gemini-3-1-pro-rag-v3", // strLF 39.2, table leader
  "gemini-3-1-pro", // 37.2 bare - the v3-vs-bare pair is the open question
  "claude-opus-5-rag", // 32.9, Claude's best arm (v1! v3 hurts Claude)
];

/** Hard budget cap in USD. The stop rule below makes exceeding it impossible. */
const HARD_CAP_USD = 15;
/** Prompts per slice between spend re-measurements. */
const SLICE_SIZE = 60;
/**
 * Output budget per train generation, PER PROVIDER. The decision doc's 1024
 * bound holds for Claude (its answers ran ~168 out tokens on the frozen
 * bank, so 1024 bounds the worst case with room to spare). It does NOT hold
 * for gemini-3.1-pro-preview: its hidden reasoning trace bills against the
 * completion budget (frontier-targets.ts documents the same trap), and the
 * first run at 1024 pinned tokenCountOut at exactly 1020 on every long
 * answer - truncated mid-trace, with reasoning fragments leaking into the
 * visible text. Gemini therefore keeps the 4096 budget its frozen-bank runs
 * used (measured means ~1100-1155 out); the $15 cap stays safe because the
 * slice stop rule below prices the worst case with THIS SAME number.
 */
function trainMaxTokensFor(candidate: { provider: string }): number {
  return candidate.provider === "google" ? 4096 : 1024;
}
/** Worst-case assumed input tokens per call for the stop rule. */
const WORST_CASE_IN = 4096;
/**
 * Concurrent generations per candidate within a slice. Overridable because
 * gemini-3.1-pro-preview's reasoning latency (~60-90s/call) makes low
 * concurrency a multi-hour run; failures from over-concurrency (429s) are
 * safe - the run is idempotent and a re-run at lower concurrency fills gaps.
 */
const CONCURRENCY = Number(process.env.TRAIN_CONCURRENCY ?? 4);

/** Same K values as the chat route - the composition being reproduced. */
const GOLD_K = 8;
const RAG_K = 4;

function log(...args: unknown[]) {
  console.log(...args);
}

function keyForProvider(provider: string): string | undefined {
  switch (provider) {
    case "anthropic":
      return process.env.ANTHROPIC_API_KEY;
    case "openai":
      return process.env.OPENAI_API_KEY;
    case "google":
      return process.env.GOOGLE_GENERATIVE_AI_API_KEY;
    case "openai-compatible":
      return (
        process.env.OPENAI_COMPATIBLE_API_KEY ?? process.env.TOGETHER_API_KEY
      );
    case "openrouter":
      // OpenRouter only - never another vendor's key, matching resolveModel.
      return process.env.OPENROUTER_API_KEY;
    default:
      return undefined;
  }
}

// ─── POOL ───────────────────────────────────────────────────────────────────

async function pool() {
  // Additive flag, set idempotently: decided slugs in, everything else out.
  const cleared = await prisma.candidateModel.updateMany({
    where: { slug: { notIn: DECIDED_POOL_SLUGS }, inPairingPool: true },
    data: { inPairingPool: false },
  });
  const set = await prisma.candidateModel.updateMany({
    where: { slug: { in: DECIDED_POOL_SLUGS }, archived: false },
    data: { inPairingPool: true },
  });
  log(
    `pairing pool: flagged ${set.count} arm(s) in, cleared ${cleared.count} stale flag(s)`,
  );
  const rows = await prisma.candidateModel.findMany({
    where: { inPairingPool: true },
    select: { slug: true, name: true },
  });
  for (const r of rows) log(`  in pool: ${r.slug.padEnd(26)} ${r.name}`);
  if (rows.length !== DECIDED_POOL_SLUGS.length) {
    log(
      `  !! expected ${DECIDED_POOL_SLUGS.length} pool arms - register the missing candidate(s) first`,
    );
  }
}

// ─── TRAIN PROMPTS (zero-gold first) ────────────────────────────────────────

interface TrainPrompt {
  id: string;
  promptId: string;
  text: string;
  bucket: EvalBucket | null;
  goldCount: number;
}

async function trainPrompts(): Promise<TrainPrompt[]> {
  const rows = await prisma.prompt.findMany({
    where: { isHoldout: false, language: "igala" },
    select: {
      id: true,
      promptId: true,
      text: true,
      bucket: true,
      _count: { select: { coldAuthorAnswers: { where: { isDemo: false } } } },
    },
    orderBy: { promptId: "asc" },
  });
  const prompts = rows.map((r) => ({
    id: r.id,
    promptId: r.promptId,
    text: r.text,
    bucket: r.bucket,
    goldCount: r._count.coldAuthorAnswers,
  }));
  // Tranche 1 = zero-gold prompts (stable sort keeps promptId order inside
  // each tranche, so slices are reproducible across resumed runs).
  return [
    ...prompts.filter((p) => p.goldCount === 0),
    ...prompts.filter((p) => p.goldCount > 0),
  ];
}

// ─── RETRIEVAL (shared per prompt, cached across candidates) ────────────────

/**
 * Mirror of the chat route's loadGoldPool() (src/app/api/arena/chat/route.ts),
 * same as frontier-fill.ts: demo rows out, consentTraining honoured IN THE
 * QUERY, isHoldout taken from the prompt.
 */
async function loadGoldPool(): Promise<GoldPoolEntry[]> {
  const rows = await prisma.coldAuthorAnswer.findMany({
    where: { isDemo: false, consentTraining: true },
    select: {
      id: true,
      promptId: true,
      answerText: true,
      bucket: true,
      consentTraining: true,
      isDemo: true,
      verificationStatus: true,
      prompt: {
        select: { promptId: true, text: true, isHoldout: true, bucket: true },
      },
    },
  });
  return rows.map((r) => ({
    id: r.id,
    promptId: r.promptId,
    promptRef: r.prompt.promptId,
    promptText: r.prompt.text,
    answerText: r.answerText,
    bucket: r.bucket ?? r.prompt.bucket,
    isHoldout: r.prompt.isHoldout,
    isDemo: r.isDemo,
    consentTraining: r.consentTraining,
    verificationStatus: r.verificationStatus,
  }));
}

interface V1Retrieval {
  ragContext: RagChunk[];
  goldExamples: GoldExample[];
}

/** v1 assembly for one train prompt, exactly as the chat route builds it. */
async function v1RetrievalFor(
  prompt: TrainPrompt,
  goldPool: GoldPoolEntry[],
): Promise<V1Retrieval> {
  let ragContext: RagChunk[] = [];
  try {
    const entries = await searchRag(prompt.text, "igala", RAG_K);
    ragContext = entries.map((e) => ({
      id: e.id,
      content: e.content,
      topic: e.topic,
      chunkType: e.chunkType,
    }));
  } catch (e) {
    log(
      `  !! searchRag unavailable for ${prompt.promptId}: ${(e as Error).message}`,
    );
  }

  const retrieved = retrieveGoldExamples(
    // The REAL prompt identity. isHoldout false: the frozen-bank source
    // exclusion (rule 2) still holds by default, and rule 1 (own gold never
    // served) is unconditional.
    {
      promptId: prompt.id,
      text: prompt.text,
      bucket: prompt.bucket,
      isHoldout: false,
    },
    goldPool,
    { k: GOLD_K },
  );
  // Hard assertion, same policy as frontier-fill: refuse to spend a cent on
  // a call that would show a speaker's own gold back to its author.
  for (const ex of retrieved.examples) {
    if (ex.promptId === prompt.id) {
      throw new Error(
        `OWN-GOLD LEAK: retrieval returned the prompt's own gold (${ex.id})`,
      );
    }
  }

  return {
    ragContext,
    goldExamples: retrieved.examples.map((e) => ({
      id: e.id,
      question: e.question,
      answer: e.answer,
    })),
  };
}

// ─── COST: measured + worst case ────────────────────────────────────────────

/**
 * MEASURED spend so far: every non-demo output the pool arms hold on train
 * prompts, priced from its stored token counts. Recomputed from the DB after
 * every slice, so resumed/parallel runs share one budget and the cap can
 * never be reset by a restart.
 */
async function measuredTrainSpendUsd(
  candidateIds: string[],
  trainPromptIds: string[],
): Promise<number> {
  const outputs = await prisma.modelOutput.findMany({
    where: {
      candidateModelId: { in: candidateIds },
      promptId: { in: trainPromptIds },
      isDemo: false,
    },
    select: { modelId: true, tokenCountIn: true, tokenCountOut: true },
  });
  let usd = 0;
  for (const o of outputs) {
    usd += estimateGenerationCostUsd({
      modelId: o.modelId,
      tokensIn: o.tokenCountIn,
      tokensOut: o.tokenCountOut,
    });
  }
  return usd;
}

/** Worst-case USD for one call of a candidate under the train token caps. */
function worstCaseCallUsd(candidate: {
  provider: string;
  baseModelId: string;
}): number {
  const p = priceForModel(candidate.baseModelId);
  return (
    (WORST_CASE_IN / 1_000_000) * p.input +
    (trainMaxTokensFor(candidate) / 1_000_000) * p.output
  );
}

// ─── GENERATE ───────────────────────────────────────────────────────────────

interface CandidateReport {
  slug: string;
  mode: string;
  created: number;
  existing: number;
  failed: number;
  costUsd: number;
  tokensIn: number;
  tokensOut: number;
  skipped: string | null;
}

interface PoolCandidate {
  id: string;
  slug: string;
  name: string;
  family: string;
  provider: string;
  baseModelId: string;
  apiEndpoint: string | null;
  archived: boolean;
  ragEnabled: boolean;
  versionLabel: string | null;
  decodingParams: unknown;
}

async function generate(slugs: string[]) {
  const prompts = await trainPrompts();
  const zeroGold = prompts.filter((p) => p.goldCount === 0).length;
  log(
    `train prompts: ${prompts.length} (${zeroGold} zero-gold served first)\n` +
      `caps: $${HARD_CAP_USD} hard, maxTokens 4096 (google) / 1024 (others), slice ${SLICE_SIZE}\n`,
  );

  const candidates: PoolCandidate[] =
    slugs.length > 0
      ? await prisma.candidateModel.findMany({ where: { slug: { in: slugs } } })
      : await prisma.candidateModel.findMany({
          where: { inPairingPool: true, archived: false },
        });
  if (candidates.length === 0) {
    log("no candidates to generate for - run the pool step first");
    return;
  }

  const reports = new Map<string, CandidateReport>();
  const live: PoolCandidate[] = [];

  for (const candidate of candidates) {
    const report: CandidateReport = {
      slug: candidate.slug,
      mode: servingModeFor(candidate),
      created: 0,
      existing: 0,
      failed: 0,
      costUsd: 0,
      tokensIn: 0,
      tokensOut: 0,
      skipped: null,
    };
    reports.set(candidate.slug, report);

    if (candidate.archived) {
      report.skipped = "archived candidate";
      continue;
    }
    const decoding = (candidate.decodingParams ?? {}) as Record<
      string,
      unknown
    >;
    if (decoding.temperature !== 0 && decoding.temperature !== null) {
      // Same trust-but-verify as frontier-fill: a silently non-zero
      // temperature would make every cross-arm comparison partly a decoding
      // comparison. null is the sanctioned exception (Claude Opus 5 rejects
      // the parameter).
      report.skipped = `temperature is ${String(decoding.temperature)}, expected 0 (or null)`;
      continue;
    }
    if (!keyForProvider(candidate.provider)) {
      report.skipped = `no API key for provider "${candidate.provider}"`;
      continue;
    }
    // One cheap probe before committing to hundreds of calls: a dead key
    // should cost one failed request and one clear line. The error is
    // reported verbatim - "which exact error did the provider return" is
    // part of the deliverable.
    try {
      await generateForCandidate(
        {
          provider: candidate.provider,
          baseModelId: candidate.baseModelId,
          apiEndpoint: candidate.apiEndpoint,
          decodingParams: { ...decoding, maxTokens: 32 },
        },
        { userMessage: "hi" },
      );
      live.push(candidate);
    } catch (e) {
      report.skipped = `provider probe failed: ${(e as Error).message.slice(0, 300)}`;
    }
  }

  for (const r of reports.values()) {
    if (r.skipped) log(`== ${r.slug}: SKIPPED (${r.skipped})`);
  }

  const trainPromptIds = prompts.map((p) => p.id);
  const candidateIds = live.map((c) => c.id);

  // What still needs generating, per candidate (idempotent resume).
  const doneByCandidate = new Map<string, Set<string>>();
  for (const c of live) {
    const existing = await prisma.modelOutput.findMany({
      where: { candidateModelId: c.id, isDemo: false },
      select: { promptId: true },
    });
    doneByCandidate.set(c.slug, new Set(existing.map((e) => e.promptId)));
  }

  // Retrieval caches shared across candidates and slices.
  let goldPool: GoldPoolEntry[] | null = null;
  const v1Cache = new Map<string, V1Retrieval>();
  const v2Cache = new Map<string, RetrievalV2Result>();

  const abandoned = new Set<string>();
  // USD already written to CostEntry per candidate (so each slice's entry
  // records only that slice's spend, not a cumulative re-count).
  const ledgered = new Map<string, number>();

  let sliceIndex = 0;
  for (let start = 0; start < prompts.length; start += SLICE_SIZE) {
    const slice = prompts.slice(start, start + SLICE_SIZE);
    sliceIndex++;

    // ── the stop rule, evaluated BEFORE any money is spent on this slice ──
    const measured = await measuredTrainSpendUsd(candidateIds, trainPromptIds);
    let sliceWorstCase = 0;
    for (const c of live) {
      if (abandoned.has(c.slug)) continue;
      const done = doneByCandidate.get(c.slug)!;
      const missing = slice.filter((p) => !done.has(p.id)).length;
      sliceWorstCase += missing * worstCaseCallUsd(c);
    }
    log(
      `\n─ slice ${sliceIndex} (${slice[0]?.promptId} .. ${slice[slice.length - 1]?.promptId}): ` +
        `measured so far $${measured.toFixed(2)}, worst case this slice $${sliceWorstCase.toFixed(2)}`,
    );
    if (measured + sliceWorstCase > HARD_CAP_USD) {
      log(
        `HALT: $${measured.toFixed(2)} measured + $${sliceWorstCase.toFixed(2)} worst case ` +
          `would risk the $${HARD_CAP_USD} cap. ${prompts.length - start} prompts left ungenerated; ` +
          `re-run after reviewing spend to continue.`,
      );
      break;
    }
    if (sliceWorstCase === 0 && live.every((c) => abandoned.has(c.slug))) {
      log("HALT: every candidate abandoned.");
      break;
    }

    for (const candidate of live) {
      if (abandoned.has(candidate.slug)) continue;
      const report = reports.get(candidate.slug)!;
      const done = doneByCandidate.get(candidate.slug)!;
      const mode = servingModeFor(candidate);
      const decoding = (candidate.decodingParams ?? {}) as Record<
        string,
        unknown
      >;
      const todo = slice.filter((p) => {
        if (done.has(p.id)) {
          report.existing++;
          return false;
        }
        return true;
      });
      if (todo.length === 0) continue;
      log(`  ${candidate.slug} [${mode}]: ${todo.length} to generate`);

      const sliceStartFailures = report.failed;
      const sliceStartCreated = report.created;

      const maxTokens = trainMaxTokensFor(candidate);

      const generateOne = async (prompt: TrainPrompt) => {
        let gen;
        let ragContextIds: string[];

        if (mode === "rag-v2" || mode === "rag-v3") {
          if (!v2Cache.has(prompt.promptId)) {
            v2Cache.set(
              prompt.promptId,
              // The human slug - buildRetrievalV2 keys its guards on prompt
              // slugs. isHoldout false: train prompt, no frozen-bank leak
              // guard, but the gold module's own-gold rule still applies.
              await buildRetrievalV2(prisma, {
                promptId: prompt.promptId,
                text: prompt.text,
                bucket: prompt.bucket,
                isHoldout: false,
              }),
            );
          }
          const v2 = v2Cache.get(prompt.promptId)!;
          gen = await generateForCandidate(
            {
              ...candidate,
              decodingParams: { ...decoding, maxTokens },
            } as CandidateLike,
            {
              userMessage: buildUserTurnV2(prompt.text, v2, prompt.bucket),
              goldExamples: v2.exampleTurns,
              systemPromptOverride:
                mode === "rag-v3" ? IGALA_SYSTEM_V3 : IGALA_SYSTEM_V2,
            },
          );
          ragContextIds = v2.contextIds;
        } else if (mode === "rag-v1") {
          goldPool ??= await loadGoldPool();
          if (!v1Cache.has(prompt.id)) {
            v1Cache.set(prompt.id, await v1RetrievalFor(prompt, goldPool));
          }
          const v1 = v1Cache.get(prompt.id)!;
          gen = await generateForCandidate(
            {
              ...candidate,
              decodingParams: { ...decoding, maxTokens },
            } as CandidateLike,
            {
              userMessage: prompt.text,
              ragContext: v1.ragContext,
              goldExamples: v1.goldExamples,
            },
          );
          ragContextIds = gen.ragContextIds;
        } else {
          gen = await generateForCandidate(
            {
              ...candidate,
              decodingParams: { ...decoding, maxTokens },
            } as CandidateLike,
            { userMessage: prompt.text },
          );
          ragContextIds = gen.ragContextIds;
        }

        if (!gen.text?.trim()) {
          // A reasoning trace can eat the whole completion budget and return
          // "". Storing an empty output would poison the annotation queue, so
          // it is a failure (the token spend still counts via the provider).
          throw new Error(
            `empty output (maxTokens ${maxTokens} likely consumed by reasoning trace)`,
          );
        }
        if (gen.tokensOut != null && gen.tokensOut >= maxTokens - 8) {
          // Completion pinned at the cap = truncated mid-answer (the first
          // 1024-cap run stored reasoning fragments this way). Refuse to
          // store it; a truncated output is worse than a missing one.
          throw new Error(
            `truncated output (tokensOut ${gen.tokensOut} hit the ${maxTokens} cap)`,
          );
        }

        await prisma.modelOutput.create({
          data: {
            promptId: prompt.id,
            model: candidate.family,
            modelId: gen.modelId,
            candidateModelId: candidate.id,
            bucket: prompt.bucket,
            outputText: gen.text,
            ragContextIds,
            tokenCountIn: gen.tokensIn ?? null,
            tokenCountOut: gen.tokensOut ?? null,
            latencyMs: gen.latencyMs,
            isDemo: false,
          },
        });
        done.add(prompt.id);
        report.costUsd += estimateGenerationCostUsd({
          modelId: gen.modelId,
          tokensIn: gen.tokensIn,
          tokensOut: gen.tokensOut,
        });
        report.tokensIn += gen.tokensIn ?? 0;
        report.tokensOut += gen.tokensOut ?? 0;
        report.created++;
        log(
          `    ok  ${prompt.promptId.padEnd(24)} ${gen.text.replace(/\s+/g, " ").slice(0, 56)}`,
        );
      };

      // Modest concurrency per candidate; abandon if a slice produces only
      // failures (dead model id / hard quota) so we never burn a whole bank
      // of identical errors.
      for (let i = 0; i < todo.length; i += CONCURRENCY) {
        const chunk = todo.slice(i, i + CONCURRENCY);
        await Promise.all(
          chunk.map(async (prompt) => {
            try {
              await generateOne(prompt);
            } catch (e) {
              report.failed++;
              log(
                `    ERR ${prompt.promptId}: ${(e as Error).message.slice(0, 140)}`,
              );
            }
          }),
        );
        // SLICE-LOCAL abandon: a provider that stops serving mid-run (the
        // observed case - Gemini's daily quota exhausted after 145 outputs)
        // must not churn 3-retry failures through the whole remaining bank
        // just because earlier slices succeeded.
        if (
          report.failed - sliceStartFailures >= 12 &&
          report.created === sliceStartCreated
        ) {
          report.skipped =
            "abandoned: only failures in this slice (quota exhausted or provider down) - re-run later to resume";
          abandoned.add(candidate.slug);
          log(`    -> abandoning ${candidate.slug}`);
          break;
        }
      }
    }

    // ── ledger: one CostEntry per candidate per slice with real spend ──────
    // AUDIT TRAIL ONLY. These category "eval_generation" rows record what this
    // run spent per candidate, but the outputs they paid for are stored as
    // ModelOutput rows with token counts, and /api/arena/costs prices those
    // live. The route therefore EXCLUDES eval_generation from its consumption
    // sum - counting both would double-count every dollar here. Keep writing
    // them (they are the per-slice record); do not add them to any total.
    for (const candidate of live) {
      const report = reports.get(candidate.slug)!;
      const sliceCost = report.costUsd - (ledgered.get(candidate.slug) ?? 0);
      if (sliceCost > 0) {
        await prisma.costEntry.create({
          data: {
            category: "eval_generation",
            provider: candidate.provider,
            label: `train-queue-fill slice ${sliceIndex}: ${candidate.slug} (annotation pivot, train prompts)`,
            amountUsd: roundUsd(sliceCost),
            estimated: true,
            refType: "train_queue_fill",
            refId: candidate.id,
          },
        });
        ledgered.set(candidate.slug, report.costUsd);
      }
    }
  }

  // ─── report ──────────────────────────────────────────────────────────────
  const finalMeasured = await measuredTrainSpendUsd(
    candidateIds,
    trainPromptIds,
  );
  log("\n\nTRAIN QUEUE FILL SUMMARY");
  for (const r of reports.values()) {
    const counts = `created=${String(r.created).padStart(3)} existing=${String(r.existing).padStart(3)} failed=${String(r.failed).padStart(3)}`;
    const tail = r.skipped
      ? `SKIPPED: ${r.skipped}`
      : `~$${roundUsd(r.costUsd).toFixed(2)} this run (${r.tokensIn} in / ${r.tokensOut} out)`;
    log(`  ${r.slug.padEnd(26)} [${r.mode.padEnd(8)}] ${counts}  ${tail}`);
  }
  log(
    `\nMeasured pool-arm spend on train prompts (all runs): $${finalMeasured.toFixed(2)} ` +
      `of the $${HARD_CAP_USD} cap (rates from src/lib/arena/pricing.ts; unlisted model ids ` +
      `bill at the $1/$3 default - a floor, which is why the cap is enforced by rule).`,
  );
}

// ─── entrypoint ─────────────────────────────────────────────────────────────

async function main() {
  const [step, ...rest] = process.argv.slice(2);
  switch (step) {
    case "pool":
      await pool();
      break;
    case "generate":
      await generate(rest);
      break;
    case "all":
      await pool();
      await generate(rest);
      break;
    default:
      log("Usage: train-queue-fill.ts <pool|generate|all> [slug ...]");
      process.exitCode = 1;
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
